/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
export interface AdminUpdateUserInput {
    /**
     * @minLength 2
     * @maxLength 120
     */
    name?: string;
    username?: string | null;
    email?: string | null;
    phone?: string | null;
    addressLine?: string | null;
    bio?: string | null;
    isAdmin?: boolean;
    /**
     * Новый пароль (минимум 6 символов)
     * @minLength 6
     * @maxLength 200
     */
    password?: string;
}
//# sourceMappingURL=adminUpdateUserInput.d.ts.map