/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
export type AdminDeleteTask200 = {
    ok: boolean;
};
//# sourceMappingURL=adminDeleteTask200.d.ts.map