/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
export type AdminStatsTasksByStatus = {
    open: number;
    in_progress: number;
    awaiting_payment: number;
    completed: number;
    cancelled: number;
};
//# sourceMappingURL=adminStatsTasksByStatus.d.ts.map