/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
export type AdminListUsersParams = {
    search?: string;
};
//# sourceMappingURL=adminListUsersParams.d.ts.map