/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
export type EscrowStatus = (typeof EscrowStatus)[keyof typeof EscrowStatus] | null;
export declare const EscrowStatus: {
    readonly none: "none";
    readonly held: "held";
    readonly released: "released";
    readonly refunded: "refunded";
};
//# sourceMappingURL=escrowStatus.d.ts.map