/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskMessage } from "./taskMessage";
export type ListTaskMessages200 = {
    messages: TaskMessage[];
};
//# sourceMappingURL=listTaskMessages200.d.ts.map