/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskCategory } from "./taskCategory";
import type { TaskStatus } from "./taskStatus";
export type ListTasksParams = {
    category?: TaskCategory;
    status?: TaskStatus;
    search?: string;
    /**
     * @minimum 50
     * @maximum 50000
     */
    maxDistanceMeters?: number;
};
//# sourceMappingURL=listTasksParams.d.ts.map