/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskCategory } from "./taskCategory";
import type { TaskStatus } from "./taskStatus";
import type { User } from "./user";
export interface Task {
    id: string;
    title: string;
    description: string;
    category: TaskCategory;
    status: TaskStatus;
    /** Исполнитель отметил задание выполненным и ждёт подтверждения заказчика */
    awaitingReview: boolean;
    /** Цена, предложенная заказчиком, в тенге */
    priceTenge: number;
    /** Использовать безопасную сделку (с комиссией платформы) */
    useEscrow: boolean;
    address: string;
    /** Расстояние от центра района в метрах */
    distanceMeters: number;
    /**
     * @minimum -90
     * @maximum 90
     */
    latitude: number;
    /**
     * @minimum -180
     * @maximum 180
     */
    longitude: number;
    deadline?: Date | null;
    owner: User;
    executor?: User | null;
    offerCount: number;
    createdAt: Date;
    paymentPhone?: string | null;
    paymentAmount?: number | null;
}
//# sourceMappingURL=task.d.ts.map