/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
import type { Escrow } from "./escrow";
import type { Offer } from "./offer";
import type { Task } from "./task";
export interface TaskDetail {
    task: Task;
    offers: Offer[];
    escrow: Escrow;
}
//# sourceMappingURL=taskDetail.d.ts.map