/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
/**
 * Категория задания
 */
export type TaskCategory = (typeof TaskCategory)[keyof typeof TaskCategory];
export declare const TaskCategory: {
    readonly walk_dog: "walk_dog";
    readonly groceries: "groceries";
    readonly parcel_pickup: "parcel_pickup";
    readonly plant_care: "plant_care";
    readonly pet_sitting: "pet_sitting";
    readonly errand: "errand";
    readonly cleaning_help: "cleaning_help";
    readonly other: "other";
};
//# sourceMappingURL=taskCategory.d.ts.map