/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
export interface TaskMessage {
    id: string;
    taskId: string;
    fromUserId: string;
    fromUserName: string;
    text: string;
    createdAt: Date;
}
//# sourceMappingURL=taskMessage.d.ts.map