/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
export interface TelegramStatus {
    linked: boolean;
    /** Бот настроен на сервере */
    configured: boolean;
    botUsername: string;
    /** Активный код привязки, если ещё не использован */
    linkToken?: string | null;
    /** Готовая ссылка t.me с deep-link кодом */
    linkUrl?: string | null;
}
//# sourceMappingURL=telegramStatus.d.ts.map