/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
import type { Review } from "./review";
import type { User } from "./user";
export interface UserProfile {
    user: User;
    recentReviews: Review[];
}
//# sourceMappingURL=userProfile.d.ts.map