/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
export type UserCity = (typeof UserCity)[keyof typeof UserCity] | null;
export declare const UserCity: {
    readonly Астана: "Астана";
    readonly Алматы: "Алматы";
    readonly Шымкент: "Шымкент";
    readonly Қарағанды: "Қарағанды";
    readonly Атырау: "Атырау";
    readonly Актобе: "Актобе";
    readonly Тараз: "Тараз";
    readonly Павлодар: "Павлодар";
    readonly Семей: "Семей";
    readonly Өскемен: "Өскемен";
};
//# sourceMappingURL=userCity.d.ts.map