/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
export type WalletTransactionKind = (typeof WalletTransactionKind)[keyof typeof WalletTransactionKind];
export declare const WalletTransactionKind: {
    readonly deposit: "deposit";
    readonly hold: "hold";
    readonly release: "release";
    readonly refund: "refund";
    readonly commission: "commission";
    readonly payout: "payout";
};
//# sourceMappingURL=walletTransactionKind.d.ts.map