/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Соседский помощник API
 * OpenAPI spec version: 0.1.0
 */
import type { WalletTransactionKind } from "./walletTransactionKind";
export interface WalletTransaction {
    id: string;
    kind: WalletTransactionKind;
    amountTenge: number;
    taskId?: string | null;
    description: string;
    createdAt: Date;
}
//# sourceMappingURL=walletTransaction.d.ts.map